# Generated by Django 5.1.6 on 2026-03-26 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_appointment_queue_status_appointment_time_slot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientSignupOTP",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("mobile_number", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("history", models.TextField(blank=True, default="")),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
            ],
        ),
    ]
