# Generated by Django 5.1.6 on 2026-03-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_patientsignupotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalrecord",
            name="record_file",
            field=models.FileField(blank=True, null=True, upload_to="medical_records/"),
        ),
    ]
