# Generated by Django 5.1.6 on 2026-03-26 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_medicalrecord_record_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="appointment",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.appointment"),
        ),
    ]
