# Generated by Django 5.1.6 on 2026-03-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_billing_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_no_show",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="pre_checkin_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reason",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
