# Generated by Django 5.1.6 on 2026-03-26 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_appointment_reason_pre_checkin_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(choices=[("admin", "Admin"), ("frontdesk", "Front Desk"), ("doctor", "Doctor"), ("patient", "Patient"), ("attendant", "Attendant")], max_length=15),
        ),
        migrations.CreateModel(
            name="FamilyAccess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("relation", models.CharField(blank=True, default="", max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("attendant_user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="family_links", to="api.user")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendant_links", to="api.patient")),
            ],
            options={"unique_together": {("attendant_user", "patient")}},
        ),
    ]
