# Generated by Django 5.1.6 on 2026-03-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_familyaccess_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familyaccess",
            name="relation",
            field=models.CharField(blank=True, choices=[("father", "Father"), ("mother", "Mother"), ("son", "Son"), ("daughter", "Daughter"), ("brother", "Brother"), ("sister", "Sister"), ("other", "Other")], default="other", max_length=50),
        ),
    ]
