# Generated by Django 6.0.3 on 2026-06-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_patient_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='payment_method',
            field=models.CharField(blank=True, default='Cash', max_length=20),
        ),
    ]
