# Generated by Django 6.0.3 on 2026-07-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_billing_payment_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyAccess',
        ),
    ]
