from django.urls import path
from .views import (
    activity_logs,
    admission_detail,
    admissions,
    add_patient,
    appointment_detail,
    appointments,
    billing,
    billing_detail,
    billing_invoice,
    custom_login,
    dashboard_summary,
    attendant_dashboard,
    attendant_users,
    attendant_family_members,
    doctor_available_slots,
    doctor_dashboard,
    doctors,
    family_access,
    family_access_detail,
    get_patients,
    medical_records,
    patient_dashboard,
    patient_detail,
    patient_users,
    reset_patient_login_password,
    request_patient_signup_otp,
    prescriptions,
    queue_summary,
    register,
    request_password_reset,
    reset_password,
    secure_data,
    api_index,
    verify_patient_signup_otp,
)

urlpatterns = [
    path("", api_index),
    path("register/", register),
    path("forgot-password/", request_password_reset),
    path("reset-password/", reset_password),
    path("patient-signup/", request_patient_signup_otp),
    path("patient-signup/verify/", verify_patient_signup_otp),
    path("summary/", dashboard_summary),
    path("queue-summary/", queue_summary),
    path("activity-logs/", activity_logs),
    path("patient-users/", patient_users),
    path("attendant-users/", attendant_users),
    path("attendant-family-members/", attendant_family_members),
    path("family-access/", family_access),
    path("family-access/<int:link_id>/", family_access_detail),
    path("patient-users/<int:user_id>/reset-password/", reset_patient_login_password),
    path("doctors/", doctors),
    path("doctors/<int:doctor_id>/available-slots/", doctor_available_slots),
    path("patients/", get_patients),
    path("patients/<int:patient_id>/", patient_detail),
    path("add-patient/", add_patient),
    path("appointments/", appointments),
    path("book-appointment/", appointments),
    path("appointments/<int:appointment_id>/", appointment_detail),
    path("billing/", billing),
    path("billing/<int:bill_id>/", billing_detail),
    path("billing/<int:bill_id>/invoice/", billing_invoice),
    path("prescriptions/", prescriptions),
    path("medical-records/", medical_records),
    path("admissions/", admissions),
    path("admissions/<int:admission_id>/", admission_detail),
    path("secure/", secure_data),
    path("login/", custom_login),
    path("doctor-dashboard/", doctor_dashboard),
    path("patient-dashboard/", patient_dashboard),
    path("attendant-dashboard/", attendant_dashboard),
]
